### PR TITLE
 added contribution link

### PR DESCRIPTION
**Pull request by souravseal99**
Issue #15 : added a link to project repo.

### CODE REVIEW

**Comment by hargup** [comment]
Hi @souravseal99 Thanks for the contribution 😄 
This looks good, merging it.

**Comment by souravseal99** [comment]
> Hi @souravseal99 Thanks for the contribution 😄 
> This looks good, merging it.

Thanks @hargup for helping me out . 

I've one or two queries about the project, can I DM you somewhere?

**Comment by hargup** [comment]
Yes please, dm me on twitter at @hargup13 or email me at mail AT hargup.in

**Comment by souravseal99** [comment]
> Yes please, dm me on twitter at @hargup13 or email me at mail AT hargup.in

Ok sure, Thanks a lot for sharing @hargup .

**Pull request merged**
